# Generated by Django 6.0.6 on 2026-06-17 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content', models.TextField(blank=True, help_text='Полный текст с форматированием, кодом, изображениями, видео', verbose_name='Контент (HTML)')),
                ('badge_text', models.CharField(blank=True, default='', max_length=50, verbose_name='Текст бейджа')),
                ('accent_color', models.CharField(default='#2d8f5e', max_length=20, verbose_name='Цвет акцента')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GoodsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('file', models.FileField(upload_to='goods_files/', verbose_name='Файл')),
                ('file_type', models.CharField(blank=True, help_text='Напр., PDF, Видео, Архив, Инструкция', max_length=100, verbose_name='Тип файла')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Файл товара',
                'verbose_name_plural': 'Файлы товаров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата покупки')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='users.goods', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_goods', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Товар пользователя',
                'verbose_name_plural': 'Товары пользователей',
                'unique_together': {('user', 'goods')},
            },
        ),
    ]
