# Generated by Django 6.0.6 on 2026-06-18 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_goods_goodsfile_usergoods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('dashboard', 'Дашборд'), ('services', 'Услуги'), ('products', 'Продукты'), ('goods', 'Товары'), ('projects', 'Проекты'), ('blog', 'Блог'), ('contacts', 'Заявки'), ('pageviews', 'Просмотры'), ('structure', 'Структура'), ('users', 'Пользователи'), ('settings', 'Настройки')], max_length=50, verbose_name='Раздел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Право доступа к разделу',
                'verbose_name_plural': 'Права доступа к разделам',
                'unique_together': {('user', 'section')},
            },
        ),
    ]
