# Generated by Django 6.0.6 on 2026-06-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cabinetpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsfile',
            name='file_type',
            field=models.CharField(blank=True, help_text='Напр., PDF, Видео, Архив', max_length=100, verbose_name='Тип файла'),
        ),
    ]
