# Generated by Django 6.0.6 on 2026-06-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_goodsfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер по продажам')], default='admin', max_length=20, verbose_name='Роль'),
        ),
    ]
