# Generated by Django 6.0.6 on 2026-06-27 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер по продажам'), ('admin', 'Администратор')], default='admin', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='ManagerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('unread', 'Не прочитано'), ('read', 'Прочитано'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='unread', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, default='', verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Предложение менеджера',
                'verbose_name_plural': 'Предложения менеджеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
