# Generated by Django 6.0.6 on 2026-06-27 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_managersuggestion_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managersuggestion',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Топик закрыт'),
        ),
        migrations.CreateModel(
            name='SuggestionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.managersuggestion', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Сообщение в предложении',
                'verbose_name_plural': 'Сообщения в предложениях',
                'ordering': ['created_at'],
            },
        ),
    ]
