# Generated by Django 6.0.6 on 2026-06-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('category_color', models.CharField(default='#a7d5b8', max_length=20, verbose_name='Цвет категории')),
                ('date', models.DateField(verbose_name='Дата')),
                ('reading_time', models.CharField(default='5 мин чтения', max_length=50, verbose_name='Время чтения')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('author_initials', models.CharField(max_length=10, verbose_name='Инициалы')),
                ('gradient_start', models.CharField(default='#0a2e33', max_length=20, verbose_name='Начальный цвет градиента')),
                ('gradient_end', models.CharField(default='#1a4a50', max_length=20, verbose_name='Конечный цвет градиента')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Блог',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки с сайта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('company', 'Компания'), ('products', 'Продукты')], default='company', max_length=20, verbose_name='Колонка')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ссылка в футере',
                'verbose_name_plural': 'Ссылки в футере',
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Ваш цифровой партнёр', max_length=200, verbose_name='Теглайн')),
                ('title', models.CharField(default='Создаём CRM, чат-ботов и сайты, которые работают на вас', max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(default='Помогаем малому и среднему бизнесу автоматизировать продажи.', verbose_name='Описание')),
                ('cta_text', models.CharField(default='Обсудить проект', max_length=100, verbose_name='Текст кнопки')),
                ('cta_link', models.CharField(default='#contact', max_length=200, verbose_name='Ссылка кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Hero-блок',
                'verbose_name_plural': 'Hero-блок',
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(help_text='Напр. #services, /blog/', max_length=200, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимая')),
            ],
            options={
                'verbose_name': 'Ссылка в навигации',
                'verbose_name_plural': 'Навигация',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Сессия')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Статистика просмотров',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Принцип',
                'verbose_name_plural': 'Принципы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='CRM', max_length=20, verbose_name='Номер')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('accent', models.CharField(default='#a7d5b8', max_length=20, verbose_name='Цвет акцента')),
                ('accent_rgb', models.CharField(default='167,213,184', max_length=30, verbose_name='RGB акцента')),
                ('badge_text', models.CharField(default='CRM', max_length=20, verbose_name='Текст бейджа')),
                ('link_text', models.CharField(default='Узнать больше', max_length=100, verbose_name='Текст ссылки')),
                ('link_url', models.CharField(default='#contact', max_length=200, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('pending', 'В планах'), ('completed', 'Завершён')], default='active', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tag1', models.CharField(blank=True, max_length=100, verbose_name='Тег 1')),
                ('tag2', models.CharField(blank=True, max_length=100, verbose_name='Тег 2')),
                ('accent_color', models.CharField(default='#e86969', max_length=20, verbose_name='Цвет акцента')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('pill_number', models.CharField(default='01', help_text='Напр. 01, 02, 03', max_length=10, verbose_name='Номер пилла')),
                ('pill_label', models.CharField(default='Ludera CRM', max_length=100, verbose_name='Лейбл пилла')),
                ('link_text', models.CharField(default='Подробнее', max_length=100, verbose_name='Текст ссылки')),
                ('link_url', models.CharField(default='#products', max_length=200, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='hello@ludera.ru', max_length=254, verbose_name='Email')),
                ('footer_description', models.TextField(default='Создаём современные цифровые решения для малого и среднего бизнеса.', verbose_name='Описание в футере')),
                ('copyright_text', models.CharField(default='© 2024 Ludera. Все права защищены.', max_length=300, verbose_name='Копирайт')),
                ('cta_title', models.CharField(default='Готовы обсудить ваш проект?', max_length=300, verbose_name='Заголовок CTA')),
                ('cta_description', models.TextField(default='Расскажите о вашей задаче — мы подберём оптимальное решение.', verbose_name='Описание CTA')),
                ('cta_button_text', models.CharField(default='hello@ludera.ru', max_length=100, verbose_name='Текст кнопки CTA')),
                ('meta_title', models.CharField(default='Ludera — CRM, чат-боты и веб-разработка для бизнеса', max_length=300, verbose_name='Meta title')),
                ('meta_description', models.TextField(default='Ludera — разработка CRM, чат-ботов и сайтов для бизнеса.', verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.product')),
            ],
            options={
                'verbose_name': 'Возможность продукта',
                'verbose_name_plural': 'Возможности продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.IntegerField(help_text='Значение от 0 до 100', verbose_name='Значение (проценты)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='main.product')),
            ],
            options={
                'verbose_name': 'Метрика продукта',
                'verbose_name_plural': 'Метрики продуктов',
            },
        ),
    ]
