# Generated by Django 6.0.6 on 2026-06-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, help_text='Полный текст статьи с форматированием', verbose_name='Контент (HTML)'),
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, help_text='Полный текст с форматированием', verbose_name='Контент (HTML)'),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, help_text='Полный текст с форматированием', verbose_name='Контент (HTML)'),
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True, help_text='Полный текст с форматированием', verbose_name='Контент (HTML)'),
        ),
    ]
