# Generated by Django 6.0.6 on 2026-06-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='panel_config',
            field=models.JSONField(blank=True, help_text='JSON с данными для дашборда на главной', null=True, verbose_name='Настройки панели'),
        ),
    ]
