# Generated by Django 6.0.6 on 2026-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_panel_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=320, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=220, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=320, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=220, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='link_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='panel_config',
            field=models.JSONField(blank=True, help_text='JSON: {"badge": "...", "chart": [50,60,...], "chart_label": "...", "metric1_label": "...", "metric1_value": 68, "metric1_suffix": "%", "metric1_change": "...", "metric2_...", "timeline_label": "...", "timeline_progress": 75, "timeline_total": 8, "timeline_done": 6, "timeline_badge": "...", "lead_label": "...", "lead_channels": 5, "lead_pills": ["green","teal",...], "footer_text": "...", "footer_dots": ["green",...]}', null=True, verbose_name='Настройки панели'),
        ),
    ]
