# Generated by Django 6.0.6 on 2026-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=320, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=220, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=320, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=220, verbose_name='Слаг'),
        ),
    ]
