# Generated by Django 6.0.6 on 2026-06-17 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tag_blogpost_created_at_blogpost_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_initials',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=320, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=220, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=320, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=220, unique=True, verbose_name='Слаг'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
