# Generated by Django 6.0.6 on 2026-06-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_project_tags_remove_blogpost_author_initials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='number',
        ),
        migrations.RemoveField(
            model_name='service',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='service',
            name='link_url',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='cta_button_text',
            field=models.CharField(default='Связаться', max_length=100, verbose_name='Текст кнопки CTA'),
        ),
    ]
