# Generated by Django 6.0.6 on 2026-06-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_link_text_remove_product_link_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero-блок', 'verbose_name_plural': 'Hero-блоки'},
        ),
    ]
