# Generated by Django 6.0.6 on 2026-06-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_herosection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_section_subtitle',
            field=models.CharField(default='Четыре принципа, на которых построена наша работа', max_length=500, verbose_name='Подзаголовок секции «О нас»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_section_title',
            field=models.CharField(default='Почему Ludera', max_length=300, verbose_name='Заголовок секции «О нас»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='blog_empty_text',
            field=models.CharField(default='Статьи скоро появятся', max_length=300, verbose_name='Текст «нет статей»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='blog_filter_all',
            field=models.CharField(default='Все', max_length=100, verbose_name='Текст фильтра «Все»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='blog_read_text',
            field=models.CharField(default='Читать', max_length=100, verbose_name='Текст «Читать»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='blog_section_subtitle',
            field=models.CharField(default='Полезные статьи, новости и кейсы от команды Ludera', max_length=500, verbose_name='Подзаголовок секции блога'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='blog_section_title',
            field=models.CharField(default='Блог', max_length=300, verbose_name='Заголовок секции блога'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email_placeholder',
            field=models.CharField(default='Email', max_length=100, verbose_name='Placeholder «Email»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_message_placeholder',
            field=models.CharField(default='Расскажите о вашем проекте...', max_length=300, verbose_name='Placeholder «Сообщение»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_name_placeholder',
            field=models.CharField(default='Ваше имя', max_length=100, verbose_name='Placeholder «Имя»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_submit_text',
            field=models.CharField(default='Отправить заявку', max_length=100, verbose_name='Текст кнопки отправки'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_success_text',
            field=models.CharField(default='Заявка отправлена! Мы свяжемся с вами в ближайшее время.', max_length=300, verbose_name='Текст об успешной отправке'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_company_title',
            field=models.CharField(default='Компания', max_length=100, verbose_name='Заголовок колонки «Компания»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_cta_label',
            field=models.CharField(default='Начните сегодня', max_length=100, verbose_name='Лейбл CTA в футере'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_products_title',
            field=models.CharField(default='Продукты', max_length=100, verbose_name='Заголовок колонки «Продукты»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='header_account_text',
            field=models.CharField(default='Личный кабинет', max_length=100, verbose_name='Текст «Личный кабинет»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='header_cta_text',
            field=models.CharField(default='Заказать демо', max_length=100, verbose_name='Текст кнопки в хедере'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='header_login_text',
            field=models.CharField(default='Войти', max_length=100, verbose_name='Текст «Войти»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='products_detail_text',
            field=models.CharField(default='Подробнее', max_length=100, verbose_name='Текст «Подробнее» в продуктах'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='products_section_subtitle',
            field=models.CharField(default='Интегрированная платформа для управления IT-продуктами', max_length=500, verbose_name='Подзаголовок секции продуктов'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='products_section_title',
            field=models.CharField(default='Наши продукты', max_length=300, verbose_name='Заголовок секции продуктов'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='projects_section_subtitle',
            field=models.CharField(default='Реальные кейсы и решения для бизнеса', max_length=500, verbose_name='Подзаголовок секции проектов'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='projects_section_title',
            field=models.CharField(default='Наши проекты', max_length=300, verbose_name='Заголовок секции проектов'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='services_detail_text',
            field=models.CharField(default='Подробнее', max_length=100, verbose_name='Текст «Подробнее» в услугах'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='services_section_title',
            field=models.CharField(default='Современные инструменты для роста вашего бизнеса', max_length=300, verbose_name='Заголовок секции услуг'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='social_linkedin_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='social_twitter_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка Twitter/X'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='social_youtube_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка YouTube'),
        ),
    ]
