# Generated by Django 6.0.6 on 2026-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sitesetting_about_section_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='nav_blog_title',
            field=models.CharField(default='Блог', max_length=100, verbose_name='Название пункта «Блог»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_products_title',
            field=models.CharField(default='Продукты', max_length=100, verbose_name='Название пункта «Продукты»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_projects_title',
            field=models.CharField(default='Проекты', max_length=100, verbose_name='Название пункта «Проекты»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_services_title',
            field=models.CharField(default='Услуги', max_length=100, verbose_name='Название пункта «Услуги»'),
        ),
    ]
