# Generated by Django 6.0.6 on 2026-06-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sitesetting_nav_blog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_verification',
            field=models.CharField(blank=True, default='', help_text='Код верификации Google Search Console', max_length=100, verbose_name='Google Search Console'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_keywords',
            field=models.CharField(blank=True, default='создание сайтов, разработка CRM, чат-боты, заказать сайт, разработка программ, веб-студия, автоматизация бизнеса', max_length=500, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1200x630px', upload_to='settings/', verbose_name='Open Graph изображение'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='yandex_verification',
            field=models.CharField(blank=True, default='', help_text='Код верификации Яндекс.Вебмастер', max_length=100, verbose_name='Yandex Webmaster'),
        ),
    ]
