# Generated by Django 6.0.6 on 2026-06-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_sitesetting_google_verification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр. Telegram, VK, Instagram', max_length=100, verbose_name='Название')),
                ('icon', models.TextField(help_text='Вставьте SVG-код иконки', verbose_name='Иконка (SVG)')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Ссылка соцсети',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='social_linkedin_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='social_twitter_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='social_youtube_url',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_analysis_label',
            field=models.CharField(default='Анализ потребностей', max_length=100, verbose_name='Метка «Анализ»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_badge',
            field=models.CharField(default='Pipeline', max_length=50, verbose_name='Бейдж ecosystem'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_client_badge',
            field=models.CharField(default='B2B / B2C', max_length=50, verbose_name='Бейдж клиента'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_client_label',
            field=models.CharField(default='Клиент', max_length=100, verbose_name='Метка «Клиент»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_custom_label',
            field=models.CharField(default='Индивидуальная разработка', max_length=100, verbose_name='Метка «Инд. разработка»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_custom_steps',
            field=models.JSONField(default=list, help_text='JSON-массив строк. По умолчанию: ["Проектирование","Дизайн","Разработка","Тестирование","Запуск"]', verbose_name='Этапы инд. разработки'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_flow_title',
            field=models.CharField(default='Client Journey', max_length=100, verbose_name='Заголовок диаграммы'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_ready_label',
            field=models.CharField(default='Готовый продукт', max_length=100, verbose_name='Метка «Готовый продукт»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_ready_steps',
            field=models.JSONField(default=list, help_text='JSON-массив строк. По умолчанию: ["Выбор решения","Подключение","Интеграция","Адаптация","Запуск"]', verbose_name='Этапы готового продукта'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_subtitle',
            field=models.CharField(default='От задачи до запуска — два пути, один результат', max_length=500, verbose_name='Подзаголовок ecosystem'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_support_label',
            field=models.CharField(default='Поддержка и развитие', max_length=100, verbose_name='Метка «Поддержка»'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_terminal_title',
            field=models.CharField(default='ludera-cli — interactive', max_length=100, verbose_name='Заголовок терминала'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ecosystem_title',
            field=models.CharField(default='Как мы работаем', max_length=300, verbose_name='Заголовок ecosystem'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_ip_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес ИП'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_ip_inn',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_ip_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Наименование ИП'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_ip_ogrnip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ОГРНИП'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_contacts_text',
            field=models.CharField(default='Контакты', max_length=100, verbose_name='Текст «Контакты» в моб. меню'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_main_text',
            field=models.CharField(default='Главная', max_length=100, verbose_name='Текст «Главная» в моб. меню'),
        ),
    ]
