# Generated by Django 6.0.6 on 2026-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sociallink_remove_sitesetting_social_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='ecosystem_custom_steps',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='ecosystem_ready_steps',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='mobile_contacts_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='mobile_main_text',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_cta_link',
            field=models.CharField(default='#contact', max_length=200, verbose_name='Ссылка кнопки Hero'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_cta_text',
            field=models.CharField(default='Обсудить проект', max_length=100, verbose_name='Текст кнопки Hero'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_description',
            field=models.TextField(default='Помогаем малому и среднему бизнесу автоматизировать продажи.', verbose_name='Описание Hero'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_tagline',
            field=models.CharField(default='Ваш цифровой партнёр', max_length=200, verbose_name='Теглайн Hero'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Создаём CRM, чат-ботов и сайты, которые работают на вас', max_length=500, verbose_name='Заголовок Hero'),
        ),
    ]
