# Generated by Django 6.0.6 on 2026-06-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_sitesetting_ecosystem_custom_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='site_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='main.sitesetting', verbose_name='Настройки сайта'),
        ),
    ]
