# Generated by Django 6.0.6 on 2026-06-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sociallink_site_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='cta_button_text',
        ),
    ]
