# Generated by Django 6.0.6 on 2026-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_sitesetting_cta_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_card1_label',
            field=models.CharField(default='Спринт', max_length=50, verbose_name='Карточка 1 — метка'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_card1_value',
            field=models.CharField(default='47', max_length=50, verbose_name='Карточка 1 — значение'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_card2_label',
            field=models.CharField(default='Команда', max_length=50, verbose_name='Карточка 2 — метка'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_card2_value',
            field=models.CharField(default='99%', max_length=50, verbose_name='Карточка 2 — значение'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_card3_label',
            field=models.CharField(default='Проекты', max_length=50, verbose_name='Карточка 3 — метка'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_card3_value',
            field=models.CharField(default='41', max_length=50, verbose_name='Карточка 3 — значение'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_card4_label',
            field=models.CharField(default='В срок', max_length=50, verbose_name='Карточка 4 — метка'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_card4_value',
            field=models.CharField(default='41/41', max_length=50, verbose_name='Карточка 4 — значение'),
        ),
    ]
