# Generated by Django 6.0.6 on 2026-06-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_sitesetting_privacy_section_1_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session_key', 'url', 'timestamp'], name='main_pagevi_session_fafb2d_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['timestamp'], name='main_pagevi_timesta_a4df72_idx'),
        ),
    ]
