# Generated by Django 6.0.6 on 2026-06-26 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=200, verbose_name='Сфера деятельности')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('company_name', models.CharField(blank=True, max_length=300, verbose_name='Наименование')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('legal_status', models.CharField(blank=True, choices=[('ip', 'ИП'), ('self_employed', 'Самозанятый'), ('individual', 'Физическое лицо')], max_length=20, verbose_name='Правовой статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'База клиентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, verbose_name='Скрипт')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('refusal', 'Отказ'), ('tz_creation', 'Создание ТЗ'), ('tz_approval', 'Согласование ТЗ'), ('contract_signing', 'Подписание договора'), ('in_progress', 'В работе'), ('completed', 'Выполнено')], default='in_progress', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='sales.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Обзвон',
                'verbose_name_plural': 'Обзвоны',
                'ordering': ['-updated_at'],
            },
        ),
    ]
