# Generated by Django 6.0.6 on 2026-06-26 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_clientdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('status', 'Смена статуса'), ('edit', 'Редактирование'), ('comment', 'Комментарий'), ('document', 'Документ'), ('call', 'Обзвон')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('detail', models.TextField(blank=True, verbose_name='Детали')),
                ('old_value', models.CharField(blank=True, max_length=500, verbose_name='Было')),
                ('new_value', models.CharField(blank=True, max_length=500, verbose_name='Стало')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales.client', verbose_name='Клиент')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность клиента',
                'verbose_name_plural': 'Активность клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
