# Generated by Django 6.0.6 on 2026-06-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_clientactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('negotiation', 'Согласование'), ('tz_creation', 'Создание ТЗ'), ('tz_approval', 'Согласование ТЗ'), ('contract_signing', 'Подписание договора'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('refusal', 'Отказ')], default='in_progress', max_length=30, verbose_name='Статус'),
        ),
    ]
