# Generated by Django 6.0.6 on 2026-06-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_client_map_link_alter_client_online_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
    ]
