# Generated by Django 6.0.6 on 2026-06-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='map_link',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Ссылка на Яндекс/2ГИС'),
        ),
        migrations.AlterField(
            model_name='client',
            name='online_booking',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Онлайн-запись'),
        ),
        migrations.AlterField(
            model_name='client',
            name='website_link',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Ссылка на сайт'),
        ),
    ]
