# Generated by Django 6.0.6 on 2026-06-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_client_map_link_alter_client_online_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён'),
        ),
    ]
