# Generated by Django 6.0.6 on 2026-06-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_client_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('negotiation', 'Согласование'), ('tz_creation', 'Создание ТЗ'), ('tz_approval', 'Согласование ТЗ'), ('contract_signing', 'Подписание договора'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('refusal', 'Отказ'), ('call_back', 'Перезвонить'), ('unavailable', 'Не доступен')], default='in_progress', max_length=30, verbose_name='Статус'),
        ),
    ]
