# Generated by Django 6.0.6 on 2026-06-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_call_status'),
        ('sales', '0010_alter_call_status'),
    ]

    operations = [
    ]
