# Generated by Django 6.0.6 on 2026-06-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_call_status'),
        ('sales', '0012_alter_call_status_board_card_chat_chatmessage_column_and_more'),
    ]

    operations = [
    ]
