# Generated by Django 6.0.6 on 2026-06-30 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_infotopic_infotopicread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['client', 'created_at'], name='sales_call_client__32e61c_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status'], name='sales_call_status_5e0b25_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['manager', 'created_at'], name='sales_call_manager_ff9df3_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_archived', 'is_deleted'], name='sales_clien_is_arch_c94efe_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_manager'], name='sales_clien_assigne_43a85e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='sales_clien_phone_680233_idx'),
        ),
    ]
